### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by ursnj** [salalo/react-leaf-polls#34]
Throwing type error on click of vote option.

![Screenshot 2022-05-09 at 11 22 43 PM](https://user-images.githubusercontent.com/28749151/167468612-17fd9ca7-d80b-487c-8a44-0700fc18abc7.png)

**Comment by asifkabani** [comment]
I am having this issue as well, any idea why? When I remove the `isVoted` or `isVotedId` it goes away.

**Comment by ursnj** [comment]
@salalo any luck on this fix ???

**Comment by salalo** [comment]
@ursnj No, I haven't worked on it yet, sorry. Hopefully I find some time soon

**Comment by ivnxyz** [comment]
I stumbled upon this issue and I think it happens when the id is a string and not a number.

**Comment by salalo** [comment]
#36 Should fix it, closing the issue.
