### ISSUE TITLE
Polls options text aligning vertically instead of taking the required width

### ISSUE THREAD

**Issue by amitbuyo2020** [salalo/react-leaf-polls#39]
Whenever a poll object is rendered on the page, the answer or the options text align themselves character by character in vertical position. For example: if i have 3 answers, Answer1, Answer2, Answer3, then these texts align themselves in vertical position like below:
A
n
s
w
e
r
1
instead of taking the width of the div in horizontal way.
![image](https://github.com/salalo/react-leaf-polls/assets/58477464/248f0eb9-3c69-4235-8fc0-5a2d49d8ad27)
. I can't figure out why this is happening. And yeah when i click on one of the answers it behaves normally like below.
![image](https://github.com/salalo/react-leaf-polls/assets/58477464/4168074d-c42e-4abb-be4f-55fd4ad927bb)

**Comment by Darshanbennur** [comment]
Was this issue solved? I'm facing the same issue

**Comment by amitbuyo2020** [comment]
> Was this issue solved? I'm facing the same issue

Nope still not figured out

**Comment by aje** [comment]
Workaround: Add this to your own css file 
```
._is6ww > p {
    overflow: visible;
    text-overflow: ellipsis;
    white-space: nowrap;
}
```
